# Generated by Django 4.2.7 on 2024-06-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Confirmado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cellphone", models.CharField(max_length=20)),
                (
                    "food_restriction",
                    models.CharField(
                        choices=[("yes", "Sim"), ("no", "Não")], max_length=3
                    ),
                ),
                (
                    "food_restriction_details",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "bringing_guest",
                    models.CharField(
                        choices=[("yes", "Sim"), ("no", "Não")], max_length=3
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=100)),
                (
                    "guest_food_restriction",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Sim"), ("no", "Não")],
                        max_length=3,
                    ),
                ),
                (
                    "guest_food_restriction_details",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "bringing_kids",
                    models.CharField(
                        choices=[("yes", "Sim"), ("no", "Não")], max_length=3
                    ),
                ),
                ("kids_ages", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
