# Generated by Django 5.0.3 on 2024-06-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirmado',
            new_name='Resposta',
        ),
    ]
