# Generated by Django 5.0.3 on 2024-07-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_confirmado_resposta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resposta",
            name="kids_ages",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
